### ISSUE TITLE
Issue when spawning character

### ISSUE THREAD

**Issue by Waiter8** [drizzle-mizzle/Character-Engine-Discord#11]
When I try to spawn a character in a discord server, it says "Failed to find a character: Something went wrong"

This is the error that was in the console:

`Response: <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/cdn-cgi/styles/challenges.css" rel="stylesheet"><meta http-equiv="refresh" content="375"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span class="icon-wrapper"><div class="heading-icon warning-icon"></div></span><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '2',cZone: "beta.character.ai",cType: 'managed',cNounce: '51302',cRay: '82748981ea7f0ffb',cHash: 'adde79d030517eb',cUPMDTk: "\/chat\/characters\/search\/?query=mouthcloud&__cf_chl_tk=1wJh.61Tf9LG0nUBo3fxcNaKamSDSUzJRAIRENajNL4-1700188073-0-gaNycGzNDRA",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '375000',cTplV: 5,cTplB: 'cf',cK: "visitor-time",fa: "\/chat\/characters\/search\/?query=mouthcloud&__cf_chl_f_tk=1wJh.61Tf9LG0nUBo3fxcNaKamSDSUzJRAIRENajNL4-1700188073-0-gaNycGzNDRA",md: "lY4_lKNbhwZhi3Zr4dceplRUgbharqyJ2jSWXiSBhgg-1700188073-0-AYmUPfOeLifYbgm_vAJN1AI_zAAaXvnuDPoVwaUg_CU3ayRSdjzqakAFkNlKnjnh40A-07hF5bGMnAKTkAx1WAU_voSAmN2cFdaWZnEsL8z-uCUOEXAQzy24RGlor8N9IGWjoh0ojSyR8lQrMznchbUBp7YbBjII-c_mXgvbt0MJUJNor48EMKCz-4taTZiCnHrTk8J_SxB0gGwIvk3ghbBfo1x4_jy5oOT5CX9FrfUJG7CIZbvWkGowJA7-ebSGIEvWbtUXhniccWpHxVI5TcyyhwyTx5gmV3blkIVBGR5_-F4LkahxC2q_Cp5btezLByw6Zp2Z-NXmBpNRI-Y-ihCsOq6dqf8gIhWDO1LOw8jbbf551dYc8LPK8X7nAxfKmhkvx5oVth26qEWaMxjmuE9hSpDjetj80y54yIP7kkyPIElPQthR-XH-mqM5ZgTsET-XL6NJINx4y2gbQJgcC6fco3vW5wdQUsR2NDgRWxOGqxitOIw8C4wHgdnVwNY_aRF91ZHRBxTxchx8fe2EBC13xnB7juNHNG--9mtKu3xJQQvn3KvESmCqQ66IWeJ9rdNjlze7tnsz1m5D_c087rz9-Ff4HJ6UVNtoMZEMxmE_vsy72HSpXeLo9VqDb0X_-CMv0lV0NdKqxO0U_2WYQTa2m_JsEQB36geSzdOJrIV5phKXYJZRezKFciMPI_am20kWuYE3tpV6ORLqLwrU7BcP3h8uYV6qrCIAq5myhHf2XxmEp8Pibf7x354p4cIi8zrO06HmGb39k7jle8M3Ma3CJ4MNDTFaTZgntfVufHKF7YaTOoj_ftNxOl6nKs9QLG1QU0u2fr3KmAMOgps9cUjjTX8HVJuZUAwKrYhGPai6FvENqtvQAAlIjdCW6-RiI-aeqjIUpViASKJwbKzBTyIQ8I3YvSpziyUdVK9cvNMwsp065jJhUfAXgoanPEmsF1xJds7jh5Rs_iKDsAo9VP2VOiugz_EROPGTJnHok9tmrR2ejZs5D9Vqs_uPlbHaQJD8-8yP-EEGS9XNYQB_PZRZLV8uUxpT-kVbTwl3wob1cqxRoF55RMt4ygcsh7uG6W-7yRGizSs-ZmpN06ViTzTE28wd8k9ZESmduAmsucY4rh7hZg1AfWi922eEJmDcSFwUH7PzH33JQmKEJJtjw8rVG9XU73luXbdB-xL4-H-5_N_6pmKifi5CgZl2pEX11T6PfGq2Ngrq1lRO44qYY8poP7Db0Z16lF8vGOpz6vLYO5vJdcjyyHiM9ITh4Czkiw04BOb39Yrbn7gjOCywVISl3SA7qQgXK7oeoilY8CWTxfev7fvRyysxNfBUBVEs2oMszgssEhdmU75e5l4Br2ZsgBhiKrjeMn1M2IKhUDandp6TaDclmuUBdncLsBH0bqY2xU4AFSE0VQVpj8lvdFGk34483LFTVVdUiD6ZQBecYwssIPx8mi_E-piF_2z1J9ARKBiNkktfCrlqhIuIST9xs3xDNcS6dyRPtIaFvA4q-5-DRp3BG5W6gijrOKJGcUVP81oNjSWhWGRQNgoKW-l0O64b9eOGcZV_vykHfCl4Fm4EqcJAvacxVNAImDzikdnre3GNoJnqaE_a3-5QqIw5DKIWWomgyDM5h2wc_8TmkIsuUiywzzB_iNf_Kczq7w9qvPxkcw8lR_xNT9ZoicFlKeHIqpDxHdx_eYLKnM7XhnEbIqopq6pgQiIM68DND-oDduwahIXiVP6S8Jx_nTezDYKvm-TMyUQ19xE06k-LciO7Xiv4B0Z-IsKKxWdHfArKRNXRvKEw2O-GqKTaXHFx7BKyva6aVkLSUuQeMK6zU-Jk7NJWx6V3SQxiA6Ql2kULV7fvXk6A_w0rtFADYRAo8ay4Ocm1uRGKZP0Q0Bf8ijxUBsV4Bx68SPlmghZJefCLICDQJtK0Syx4tahVLm89vqKi6muuRf1RzwWVtdTEcy3y345uVq_wCteysymlMcUJjBQ56Yfrs_rZaMUzRhyMtVMHqRRVXQua8iOgyTXLmF5pyv49J_c6zCh2jZhDefcgMENTBO5wJvdP0gFs5SckQgEo1jRbcs7op1dTnRJKNwQI7oWiq2lm1o7dqHosctjRw1BJso_KC9GMDelcYInwO5bqw1jgC3k3qjeTLErI8-9Pl8QrwGtYt-_5k6lpSr0nIE5H4-RBJ6EAyUzWm1PuirfLOqYk6eNAZiQfjj2fsRndNHabd0xcyC8A4DUwJLttfYPWN4N-sMIohkF2jqUevNjYuUwZQ_FsdS2z3EBJhV2MzY8t3YozFIqcubCahDQg-whL4awIoZYbf-ssjjmKRosuNRLScIlYxvCsWFnTkViGuXMf2rRvTtKNtIjZuWmTSDoWSRAxGnkcJ9gwRtenZqlSeGoiVA4RyMDO8Y3Fu9-SjaSwizVqXgA8cdcKN-5DJfKymz1w75hlDzGMbRT8WdtaSdRk2D19IAw5DBZq0o3BPAuZLEt-udjXgmVdQyzPDLrudLnZTwzs8SsgHObG66byS5bZ7rUCFsrQsKcJlr5gGbJNDgpiBcmZ9sjLUV1cv4PPUGRJnKdGnuxU_HWJeHpRXGyK5T6z9W2DwM0Lgww7kys_ThCYCMp8ZmTWZo9Iz8i0Qp1h6JoSwCe5w4ntzkOfZEwpY6a9WuaTeRbY5E4Fy8u2r3a3JQ6iivIdQ8LGn1c2RAY-ooKZS7fPNXR4C8HMZcYCK3qa0Xh16oYYcQdKPoedIiPl3RsV90C9nxaVTR7a8sQQbKDE7-M6pkeyU1Y_KBLKiiSyeOZ2sRBbE4W00ArFrRQQN78Fqeq2XAP3_XGtZc-dL_sRtM5DAz-x4vPZaG_KbKJ_Tot1c5fgPbnkx3QkNBjwffnLW_sGmFVqpc8C5PwDDN-Y6qPiHCUub5-NbwKWWJnK60XUXrlS6Q2oMqQajAe8zsDRQdDcRrPo7tLcPuqlAGQ9325B5o4oHhFgjLKjSnmyCct5UvBSSynlfkR1rSRH3ZCZqzYDI7tSr3mE3o6nAgRfn9BJ8gmFxEf7M18V6SjqbGU4jDSmN2CEfsv5AQoLGnlHiUfunG2F8OVJzAoy_78jEAVE_Vylvoe8ryBzh87n_zFLw-_59Mt2-gLZgR-HVq7AO4_MbHBDJf1iuEX8-Mk_t-LVFqkDD3DMB3-Y2kTg1D64WPowz1tEdVGaHSEFd-cq6phXRmUJpba_makCIewcS-XLSTY0c4UegSlCDEB0mcI5rpfdpfHav3CqSkNQ-BD-jdZ0ShGoTJ6OMG5AjgQ5vZiTkGc",cRq: {ru: 'aHR0cHM6Ly9iZXRhLmNoYXJhY3Rlci5haS9jaGF0L2NoYXJhY3RlcnMvc2VhcmNoLz9xdWVyeT1tb3V0aGNsb3Vk',ra: 'TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEwOS4wLjAuMCBTYWZhcmkvNTM3LjM2',rm: 'R0VU',d: 'Qwn9LQMAM2s+iu3LAWKA8UixxCjl48C9NwbHhIhkSqdEw4RM68yoTmNaPXOe5+rsxjksbBgGZvxds/Cd6ARJ8ZLWxeiYKY52hLXdi/zK2h18PBzRa/M4QNkoEt1zE13cYzs1s0IQBUPzhxaE+OgYpRc0BiaDI75kWpa+wBQuREzrPLVgXowUIHyuMrDLtE3sICrsg02FcKBQFddZc70+H239jK+qhWnRTBZ2JG5yS/TIa3mKkpeUHZ1ingQ2yot8gHlDZWkL3bSTZFYEW7AyQ9USE83wdQTbWei5t7MBIsBq57+GzA5wXNfNr9zd6rCjH1LTYXjE/FL3W+zjFcuF9ntJ43GBi8v7DIiNdn/9LRrj4+5Hw65wGGtyUC3VxmHhu7TykwtuMVzHg/4l6ai+QhA2Jl9aXTfODEkA2mFYus2+T0f9OWluRq1VTaZWiHdPo+Bwfw358cXdBgl1q+ECR7nEHkANhMEI15vvbYCU9x5lKdqztX380k60l2/0X+1wGfgf9eeamTFnW+AjrBCdlmTm3KhXovwByCbTLKGWeu6bQKa+mjK89cr0T2yrunJpXm/OqjlWzaG2eP/NIddwWw==',t: 'MTcwMDE4ODA3My4yNzEwMDA=',cT: Math.floor(Date.now() / 1000),m: '6mNKEG94MBZrlrCsKhsV3N+p3/xSJupdIoTX2bYk0Ig=',i1: 'W9xDEVwh+HNQbPn9sf0b6w==',i2: '1eIF3Ei+E3q4NwnWF5rm+A==',zh: '3MzEEr4KLflmeMqd8UHKRwLX7AlBIHlHXAkcvB3KPTI=',uh: 'wtUol4mGv0cZSkLSkCXCyreInDbxSqddIgKeJna747A=',hh: 'YfIreubNI/6hc4NG9htqteP1V6Jt4WFaxTZZalkN138=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=82748981ea7f0ffb';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/chat\/characters\/search\/?query=mouthcloud&__cf_chl_rt_tk=1wJh.61Tf9LG0nUBo3fxcNaKamSDSUzJRAIRENajNL4-1700188073-0-gaNycGzNDRA" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script><script defer src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317" integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA==" data-cf-beacon='{"rayId":"82748981ea7f0ffb","b":1,"version":"2023.10.0","token":"de6c8a8324c04a50b30bdeb96bc8d410"}' crossorigin="anonymous"></script>`

**Comment by drizzle-mizzle** [comment]
Try with the latest update and see if error is gone
