### ISSUE TITLE
chat2 is not supported (c.ai)

### ISSUE THREAD

**Issue by zombi-dev** [drizzle-mizzle/Character-Engine-Discord#12]
Please add support for chat2, as there are lots of useful features I would want.
For example, the personas feature. It would be nice if either the feature would be added as a seperate thing (command) using the c.ai API or inbuilt support for chat2 would be added. (I do not know if the personas feature still work even if the chat is coming from a seperate source)

And until chat2 support is added, some more clear instructions in the wiki about going to chat2 would be appreciated. I had to manually find out that chat and chat2 have different ID (hist) types.

I have tried putting a chat ID (hist) in a chat2 convo, but when I access a chat2 convo (prob because of the persona that I selected) it redirects me back to chat2 instead of chat. And when manually navigating to chat, it first of all ignores my selected persona and dosen't even give me the corrent chat ID (hist), still using the chat2 ID (hist).

**Comment by ThatCDdev** [comment]
Edited the comment for a better description.
(also accidentally deleted the first version :/)

**Comment by drizzle-mizzle** [comment]
It's too complicated, their new API is based on websockets, and I'm not sure if I will be able to integrate it in the bot at all. Won't say that I will not try, but no promises either.
