### ISSUE TITLE
(closed)    BOT TOKEN LONGER THAN 58 CHARACTERS

### ISSUE THREAD

**Issue by Cube9214** [drizzle-mizzle/Character-Engine-Discord#14]
RWAHLJRSAHPIRJAHPRj IT KEEPS SAYING THAT NO MATTER HOW MANY TIMES I RESET MY TOKEN AND PASTE IT BACK IN OH MY GOD HELP ME I HAVE BEEN WORKING FOR HOURS

**Comment by Cube9214** [comment]
![image](https://github.com/drizzle-mizzle/Character-Engine-Discord/assets/71666073/2e75a839-fa2a-4c99-8a39-c4a9d4a4a592)

**Comment by drizzle-mizzle** [comment]
bro, you better just use the bot that is already available on the project's server...
