### ISSUE TITLE
koboldParams all being passed as float

### ISSUE THREAD

**Issue by zifnub** [drizzle-mizzle/Character-Engine-Discord#18]
When trying out the kobold api I'm getting this on koboldccp:

`"rep_pen": 1.05, "rep_pen_slope": 0.8, "singleline": false, "temperature": 1.07, "tfs": 0.93, "top_a": 0.0, "top_k": 100.0, "top_P": 1.0, "typical": 1.0}
int expected instead of float`

I'm not sure which one it's complaining about but I'm assuming top_k.

**Comment by cha0sbuster** [comment]
Yep, it's top_k.
In `Models/KoboldAI/KoboldAiRequestParams.cs`, change Line 13 to say `int` instead of `float`, redo the build, and it works.

**Comment by zifnub** [comment]
Thanks! I gave that a try and it works now.
