### ISSUE TITLE
The .csproj file points to .net8.0 which causes issues while building the docker image.

### ISSUE THREAD

**Issue by Ryuo1** [drizzle-mizzle/Character-Engine-Discord#19]
Trying to build the image, I got errors about .net version mismatch.
The .csproj file points to .net8.0 while the Dockerfile grabs .net7.0.

**Comment by Ryuo1** [comment]
As a workaround, I changed the dotnet versions of the Dockerfile from 7.0-bullseye-slim to 8.0.

**Comment by drizzle-mizzle** [comment]
> Trying to build the image, I got errors about .net version mismatch. The .csproj file points to .net8.0 while the Dockerfile grabs .net7.0.

Yep, I forgot to update it. Will do later.
