### ISSUE TITLE
Allow changing the bot's pfp in the server

### ISSUE THREAD

**Issue by UnconsciousPebble** [drizzle-mizzle/Character-Engine-Discord#2]
If possible, it would be nice to be able to change the bot's pfp in the server after inviting it.

**Comment by drizzle-mizzle** [comment]
Just change it on https://discord.com/developers/ ...

**Comment by YellerFeller** [comment]
> If possible, it would be nice to be able to change the bot's pfp in the server after inviting it.

Are you talking about the Discord bot user or the AI Characters? I noticed as well that the profile pictures for the characters seem to be set when they are added. If the picture is updated on character.ai, re-adding the character will show the new picture, but will reset interaction history.

**Comment by UnconsciousPebble** [comment]
> Just change it on https://discord.com/developers/ ...

I was asking about the version that you are hosting.

**Comment by drizzle-mizzle** [comment]
It's impossible. Bot can't change its guild-specific avatar.
Characters' (webhooks') avatars can be changed with `/update avatar` command
