### ISSUE TITLE
" CharacterAI integration is disabled" ? I may be stupid

### ISSUE THREAD

**Issue by SkittyMeow** [drizzle-mizzle/Character-Engine-Discord#20]
when i try to spawn a character ai thing it says  CharacterAI integration is disabled, am i stupid? 😭

**Comment by ZZorRRx2** [comment]
Slightly. If you are self-hosting it may be that the puppeteer isn't operating properly. Since character.ai requires the puppeteer module to operate then there may be an error in using it.

**Comment by drizzle-mizzle** [comment]
@SkittyMeow look into your logs and check if there're any errors when you start the app
