### ISSUE TITLE
Trying to build this again, Error appearing!!

### ISSUE THREAD

**Issue by Cube9214** [drizzle-mizzle/Character-Engine-Discord#21]
![image](https://github.com/drizzle-mizzle/Character-Engine-Discord/assets/71666073/e527cfd1-d540-4e56-97c5-4a973c018cb5)

**Comment by Cube9214** [comment]
we  love 447 errors

**Comment by SoraUltimateProgrammer** [comment]
Seconding this, also happening to me

**Comment by Stoppedwumm** [comment]
Third one, it looks like most of the files are being determined as binary instead of text

**Comment by Stoppedwumm** [comment]
I recommend
```bash
sudo docker compose up
```

**Comment by Stoppedwumm** [comment]
> I recommend
> 
> ```shell
> sudo docker compose up
> ```

It may take some time, but it is working

**Comment by jesse-dot** [comment]
> > I recommend
> > ```shell
> > sudo docker compose up
> > ```
> 
> It may take some time, but it is working

how would docker compose work with this, it has no connection
