### ISSUE TITLE
Executing the run command causing it to be stuck on "Found installed browser"

### ISSUE THREAD

**Issue by crazyneverexisted** [drizzle-mizzle/Character-Engine-Discord#25]
This is what i get from running the command: Found installed browser: C:\Users\sansk\Downloads\Character-Engine-Discord-master\Character-Engine-Discord-master\puppeteer-chrome\Chromium\Win64-1270644\chrome-win\chrome.exe

**Comment by RichardHafer** [comment]
Same problem.

**Comment by drizzle-mizzle** [comment]
Try to simply launch it in WSL. Windows is way too inconsistent for thing like this.

**Comment by qn06142** [comment]
using ubuntu server, also having same error.

**Comment by qn06142** [comment]
just ran htop, what is this?
![image_2024-03-19_214441163](https://github.com/drizzle-mizzle/Character-Engine-Discord/assets/90816999/8a7cf79b-901c-48dd-8968-4b541f12e032)

**Comment by mzrtamp** [comment]
Same thing, i used the docker compose

![image](https://github.com/drizzle-mizzle/Character-Engine-Discord/assets/40928387/504e78f8-24ef-4873-9b54-e5206f9f3b6f)

**Comment by MrRubberDucky** [comment]
Can confirm above, downloads and just stalls there doing nothing. Though in my case I don't even get a message about any browser being found, it just stops after downloading, Debian 12 VM on Linux host

**Comment by h0t-ch0colate** [comment]
Same here. I'm new to this kind of thing so that might be on me, though. Using Opera GX on Windows 10.

**Comment by h0t-ch0colate** [comment]
> Same here. I'm new to this kind of thing so that might be on me, though. Using Opera GX on Windows 10.

Using WSL seems to get past this problem. I've been able to add the bot to a server, but it always gives a "The application did not respond" error. I'll keep this thread updated.

**Comment by fever308** [comment]
> > Same here. I'm new to this kind of thing so that might be on me, though. Using Opera GX on Windows 10.
> 
> Using WSL seems to get past this problem. I've been able to add the bot to a server, but it always gives a "The application did not respond" error. I'll keep this thread updated.

I tried launching with WSL and I get the same problem :/ 

<img width="1113" alt="image" src="https://github.com/drizzle-mizzle/Character-Engine-Discord/assets/89748148/9e2f779d-5cbb-4709-b783-e5a4b248f5fe">

**Comment by RichardHafer** [comment]
Yeah this whole thing is probably officially broken.
