### ISSUE TITLE
After installing chrome, just doesn't do anything

### ISSUE THREAD

**Issue by flebsybahh** [drizzle-mizzle/Character-Engine-Discord#27]
![image](https://github.com/drizzle-mizzle/Character-Engine-Discord/assets/104042871/3bd1ee21-fac8-443d-a9d0-b19fbb619ffc)
self-explementary

**Comment by TerryTime** [comment]
Same issue.

**Comment by Batin-dev** [comment]
Same problem, how we can fix?

**Comment by AkiSato120** [comment]
Have you found a solution?
