### ISSUE TITLE
Bot stopped working after the latest commit

### ISSUE THREAD

**Issue by eepytofu** [drizzle-mizzle/Character-Engine-Discord#3]
The latest commit (0485132) and the commit before it (cb0f147) broke the bot. It throws the following error when I use the slash command:

`:warning: Failed to execute command: An error occurred while saving the entity changes. See the inner exception for details.`

rolling back to commit b97f46a resolves the issue, and the bot works again.

**Comment by drizzle-mizzle** [comment]
Yeah, I make changes almost everyday, so sometimes things break, but usually being fixed in next 24 hours.
And this issue _could be actually helpful_ if you would specify the exact command caused the problem...

**Comment by darkxuin** [comment]
I had the same error when trying to spawn a c.AI character. Rolling back fixed it.

**Comment by drizzle-mizzle** [comment]
If there occurs any unhandled exception, it's being displayed in the console.
Just saying "it doesn't work" won't help to solve anything, provide the full error stack trace.

**Comment by darkxuin** [comment]
This isn't going to help so, i'm sorry. When the error happened there was nothing displayed in the console. I attempted to recreate the error by updating to the current version but, it's working fine now. I can only speculate it had something to do with running the first time.

**Comment by drizzle-mizzle** [comment]
Most likely, it's somehow related to the fact that I have changed database struct a little, made some fields nullable, but they remained non-null in you database.
I'll try to mark sensitive changes like this in description in the future.

**Comment by drizzle-mizzle** [comment]
Yeah, I only noticed that I have not included the migration in the commit where this change occurred, only in one of the following
