### ISSUE TITLE
error CS8604 when building on Windows 10 64-bit

### ISSUE THREAD

**Issue by vlbonnie7** [drizzle-mizzle/Character-Engine-Discord#32]
"\Character-Engine-Discord\Services\IntegrationsService.cs(405,28): error CS8604: Possible null r
eference argument for parameter 'node' in 'ChubCharacter.ChubCharacter(dynamic node, bool full)'. [D:\programs\Portable
Git\Character-Engine-Discord\Character-Engine-Discord.csproj]"

I'm not going to lie, I've never built anything before and I'm not terribly sure what I'm doing wrong. Sorry if this is a dumb question.

**Comment by Falow1** [comment]
Try using WSL on Windows, because it doesn't seem to be working on Windows for me it only worked on Linux

**Comment by cha0sbuster** [comment]
Make sure [you're on the right version of dotnet](https://github.com/drizzle-mizzle/Character-Engine-Discord/issues/28#issuecomment-2079093066) -- the hosting guide is out of sync with the repository at the moment.

**Comment by dantirya** [comment]
`PS F:\Git\Character Engine\Character-Engine-Discord> dotnet build Character-Engine-Discord.csproj
  Determining projects to restore...
  All projects are up-to-date for restore.
F:\Git\Character Engine\Character-Engine-Discord\Services\IntegrationsService.cs(405,28): error CS8604: Possible null r
eference argument for parameter 'node' in 'ChubCharacter.ChubCharacter(dynamic node, bool full)'. [F:\Git\Character Eng
ine\Character-Engine-Discord\Character-Engine-Discord.csproj]

Build FAILED.

F:\Git\Character Engine\Character-Engine-Discord\Services\IntegrationsService.cs(405,28): error CS8604: Possible null r
eference argument for parameter 'node' in 'ChubCharacter.ChubCharacter(dynamic node, bool full)'. [F:\Git\Character Eng
ine\Character-Engine-Discord\Character-Engine-Discord.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:05.42`
