### ISSUE TITLE
Batch copy characters and prefixes to a different channel

### ISSUE THREAD

**Issue by UnconsciousPebble** [drizzle-mizzle/Character-Engine-Discord#4]
Is it possible to add a command to batch-copy all of a channel's characters and their prefixes and other settings to another channel on the same server?

**Comment by drizzle-mizzle** [comment]
Bloat and hard to handle process.
Command for copying of only one character at once is planned.

**Comment by UnconsciousPebble** [comment]
That's nice too, looking forward to it!
