### ISSUE TITLE
Are there any plans to support TTS?

### ISSUE THREAD

**Issue by Namidachill** [drizzle-mizzle/Character-Engine-Discord#8]
Hello.
Do you plan to support voice conversation?
Any consideration for web access, etc.?
I know you are busy, but I would be happy to hear your future plans.

**Comment by drizzle-mizzle** [comment]
No, at least not in near future

**Comment by Mj83621** [comment]
If discord does have TTS, then yes, it works because tts is just typing with your voice, if you are talking about voice messages, then no.

**Comment by drizzle-mizzle** [comment]
I guess he mean the voice messages from characters

**Comment by Mj83621** [comment]
Maybe, I thought they were talking about like user TTS, like if you talk into your Phone/Computer and it works with the bot, but if they mean like the bots voice, then no, same goes for user voice messages
