### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by rayooldude** [drizzle-mizzle/Character-Engine-Discord#9]
I did: dotnet build Character-Engine-Discord.csproj but it says this:

PS C:\WINDOWS\system32\Character-Engine-Discord> dotnet build Character-Engine-Discord.csproj
MSBuild version 17.7.3+8ec440e68 for .NET
  Determining projects to restore...
  Restored C:\WINDOWS\system32\Character-Engine-Discord\Character-Engine-Discord.csproj (in 629 ms).
C:\WINDOWS\system32\Character-Engine-Discord\Handlers\ButtonsHandler.cs(104,157): error CS0103: The name 'fromChub' doe
s not exist in the current context [C:\WINDOWS\system32\Character-Engine-Discord\Character-Engine-Discord.csproj]

Build FAILED.

C:\WINDOWS\system32\Character-Engine-Discord\Handlers\ButtonsHandler.cs(104,157): error CS0103: The name 'fromChub' doe
s not exist in the current context [C:\WINDOWS\system32\Character-Engine-Discord\Character-Engine-Discord.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:08.48
![image_2023-10-17_205103695](https://github.com/drizzle-mizzle/Character-Engine-Discord/assets/148177045/b7d761f1-70da-48c0-8453-ff52b5de6170)

**Comment by drizzle-mizzle** [comment]
fixed
No idea how I pushed this
